name       : material-color-utilities-python
version    : 0.1.5
release    : 1
source     :
    - https://files.pythonhosted.org/packages/ef/da/a542b6e654eb308f32ca788ee9d9f77e2f521007e5cf7368a24ca420b760/material-color-utilities-python-0.1.5.tar.gz : 3c6f02e7ce70595885447bdef37cf76fd3628c7c95fa2198d8174c269c951fae
license    : Apache-2.0
homepage   : https://github.com/avanishsubbiah/material-color-utilities-python
component  : programming.python
summary    : Python port of material-color-utilities used for Material You colors
description: |
    Python port of material-color-utilities used for Material You colors
builddeps  :
    - python-build
    - python-installer
    - python-packaging
    - python-wheel
rundeps    :
    - python-pillow
    - python-regex
build      : |
    %python3_setup
install    : |
    %python3_install
